package tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Calculator = 0;
  public static final int InputField = 1;
  public static final int InputFieldReference = 2;
  public static final int OutputField = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe9a0b5c1b304860L, 0x8f9d25218462d604L);
    builder.put(0x6bb1116299eea086L, Calculator);
    builder.put(0x6bb1116299eee40bL, InputField);
    builder.put(0x6bb1116299f07210L, InputFieldReference);
    builder.put(0x6bb1116299ef094fL, OutputField);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
