package tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tutorial.calculator", "Calculator", 0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eea086L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:04fa5b30-1b8c-47ef-9694-b970e16c58ac(tutorial.calculator.structure)/7760002748123095174");
    b.version(2);
    b.aggregate("inputField", 0x6bb1116299eee43bL).target(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eee40bL).optional(true).ordered(true).multiple(true).origin("7760002748123112507").done();
    b.aggregate("outputField", 0x6bb1116299ef096aL).target(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299ef094fL).optional(true).ordered(true).multiple(true).origin("7760002748123122026").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tutorial.calculator", "InputField", 0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eee40bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:04fa5b30-1b8c-47ef-9694-b970e16c58ac(tutorial.calculator.structure)/7760002748123112459");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tutorial.calculator", "InputFieldReference", 0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299f07210L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:04fa5b30-1b8c-47ef-9694-b970e16c58ac(tutorial.calculator.structure)/7760002748123214352");
    b.version(2);
    b.associate("field", 0x6bb1116299f07211L).target(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eee40bL).optional(false).origin("7760002748123214353").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tutorial.calculator", "OutputField", 0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299ef094fL);
    b.class_(false, false, false);
    b.origin("r:04fa5b30-1b8c-47ef-9694-b970e16c58ac(tutorial.calculator.structure)/7760002748123121999");
    b.version(2);
    b.aggregate("expression", 0x6bb1116299ef6f45L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("7760002748123148101").done();
    return b.create();
  }
}
