package PropositionalLogic.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AtomicFormula_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new BinaryFormula_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Not_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TruthTable_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new TruthTableList_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc8418222bda489cL, 0x8be629cedccd87d2L, 0x3a1671c24b8053e9L), MetaIdFactory.conceptId(0xc8418222bda489cL, 0x8be629cedccd87d2L, 0x3a1671c24b8053fbL), MetaIdFactory.conceptId(0xc8418222bda489cL, 0x8be629cedccd87d2L, 0x3a1671c24b8053ecL), MetaIdFactory.conceptId(0xc8418222bda489cL, 0x8be629cedccd87d2L, 0x3a1671c24b80cf8dL), MetaIdFactory.conceptId(0xc8418222bda489cL, 0x8be629cedccd87d2L, 0x3cc5cf549b5b6096L)).seal();
}
