package Families.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Familiy;
  private ConceptPresentation props_Member;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Familiy:
        if (props_Familiy == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("the \"lastName\" property of the family is inherited as \"name\" from INamedConcept");
          cpb.presentationByName();
          props_Familiy = cpb.create();
        }
        return props_Familiy;
      case LanguageConceptSwitch.Member:
        if (props_Member == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("the \"firstName\" property of the member is inherited as \"name\" from INamedConcept");
          cpb.presentationByName();
          props_Member = cpb.create();
        }
        return props_Member;
    }
    return null;
  }
}
