package Persons.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Female_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Male_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new PersonRegister_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x91cc9005a0364c2eL, 0xbabb65eb287c094cL, 0x7382222671696b7aL), MetaIdFactory.conceptId(0x91cc9005a0364c2eL, 0xbabb65eb287c094cL, 0x7382222671696b79L), MetaIdFactory.conceptId(0x91cc9005a0364c2eL, 0xbabb65eb287c094cL, 0x2927891fcedcef0cL)).seal();
}
