package tutorial.calculator.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Calculator_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new InputField_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new InputFieldReference_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new OutputField_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new InputFieldReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eea086L), MetaIdFactory.conceptId(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299eee40bL), MetaIdFactory.conceptId(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299f07210L), MetaIdFactory.conceptId(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299ef094fL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe9a0b5c1b304860L, 0x8f9d25218462d604L, 0x6bb1116299f07210L)).seal();
}
