package Persons.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Female = 0;
  public static final int Male = 1;
  public static final int Person = 2;
  public static final int PersonRegister = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x91cc9005a0364c2eL, 0xbabb65eb287c094cL);
    builder.put(0x7382222671696b7aL, Female);
    builder.put(0x7382222671696b79L, Male);
    builder.put(0x7382222671696ab2L, Person);
    builder.put(0x2927891fcedcef0cL, PersonRegister);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
